# Generated by Django 5.0.2 on 2024-03-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_date_joined_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oe',
            field=models.CharField(choices=[('not', 'Not'), ('taken', 'Taken')], default='not', max_length=20),
        ),
    ]
