# Generated by Django 5.0.2 on 2024-02-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_result_process_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='stage',
            field=models.CharField(choices=[('standardize', 'Standardize'), ('measure', 'Measure'), ('control', 'Control'), ('improve', 'Improve'), ('humanresources', 'Human Resources'), ('cultural', 'Cultural'), ('technological', 'Technological'), ('structural', 'Structural')], max_length=20),
        ),
    ]
