# Generated by Django 5.0.2 on 2024-02-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_result_process_group_alter_result_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='process_group',
            field=models.CharField(blank=True, choices=[('Initiating', 'Initiating'), ('Planning', 'Planning'), ('Integration Management', 'Integration Management'), ('Executing', 'Executing'), ('Monitoring and Controlling', 'Monitoring and Controlling'), ('Closing', 'Closing')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='process_group',
            field=models.CharField(blank=True, choices=[('Initiating', 'Initiating'), ('Planning', 'Planning'), ('Integration Management', 'Integration Management'), ('Executing', 'Executing'), ('Monitoring and Controlling', 'Monitoring and Controlling'), ('Closing', 'Closing')], max_length=50, null=True),
        ),
    ]
